<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: mrdough
 * Date: Sat, 13 Apr 2024 04:40:51 +0200
 */

$conf['title'] = 'Cramify';
$conf['start'] = 'AP Study Guides Hub';
$conf['template'] = 'kiwiki';
$conf['license'] = 'cc-by-sa';
$conf['basedir'] = 'wiki';
$conf['camelcase'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'backlink,index,subscribe,unsubscribe';
$conf['target']['extern'] = '_blank';
$conf['useslash'] = 1;
$conf['send404'] = 1;
$conf['proxy']['user'] = 'MrDough';
$conf['proxy']['pass'] = '<b>c2lsbHltYW5TVEVWRTEyMw==';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['plugin']['htmlok']['htmlok'] = 1;
$conf['plugin']['mathjax']['config'] = 'MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\\\(","\\\\)"] ],
        displayMath: [ ["$$","$$"], ["\\\\[","\\\\]"] ],
        processEscapes: true
    }
});';
$conf['tpl']['kiwiki']['MainMenu'] = '';
$conf['tpl']['kiwiki']['TocMaxHeight'] = 400;
$conf['hidepages'] = '^:reports:(?:template|sidebar)';
$conf['hidepages'] = '^:(admin*|sidebar|playground|labels|templates|wiki)';