# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 04 Apr 2024 00:17:31 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

mrdough:$2y$10$TVqpmrM0IaCG9suBI2uB8.MIJczvQiUyenLvLlAks85.d.cJ.dJry:Ronnie:dagan.ronnie@gmail.com:admin,user
testacc:$2y$10$NefUg1Epd8By6vDKghb7eOM56t7QXnvfPZED91I50z/h.Xq8/8M3y:RD:dagan.ronnie@gmail.com:user
testaccount123:$2y$10$eDkz6yAVCj0GNTijIgV4je1sgq0.B2z9qc0bK8PKaxQp7mGq4ACzW:RD:ronnie.second.mail@gmail.com:user
